import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root'
})
export class SkillsService {

  constructor() { }

  skills = [
    {
      name: 'Gender Detection',
      pipeline: 0,
      notAssigned: 1,
      assigned: 16,
      longestWaitingTime: '00:02',
      nextDeadline: '11:26',
      sorting: '08:45',
      editors: 1,
      potential: 19,
      forced: 0,
      idle: 0,
      freelancer: 0,
      zeroHours: 0, zeroHoursFlag: 0,
      twoHours: 0, twoHoursFlag: 0,
      fourHours: 0, fourHoursFlag: 0,
      eightHours: 0, eightHoursFlag: 0,
      twelveHours: 161, twelveHoursFlag: 0,
      sixteenHours: 161, sixteenHoursFlag: 0,
      twentyFourHours: 174, twentFourHoursFlag: 0,
      fourtyEightHours: 174,
      seventyTwoHours: 174,
      avgIpt: 3.17,
      avgRej: 0.0000,
      templates: [
        ['Gender Detection', 'Model Detection', 'Generic Retouch', 'Model Skin Area', 'Finalize'],
        ['Gender Detection', 'Skin Processing', 'Recreate Details', 'Finalize'],
        ['Preparation', 'Gender Detection', 'Combination', 'Retouch: Garments 1', 'Retouch: Garments 2']
      ]
    },
    {
      name: 'Background Detection',
      pipeline: 0,
      notAssigned: 1,
      assigned: 16,
      longestWaitingTime: '00:02',
      nextDeadline: '11:26',
      sorting: '08:45',
      editors: 1,
      potential: 19,
      forced: 0,
      idle: 0,
      freelancer: 0,
      zeroHours: 0, zeroHoursFlag: 0,
      twoHours: 0, twoHoursFlag: 0,
      fourHours: 0, fourHoursFlag: 0,
      eightHours: 0, eightHoursFlag: 0,
      twelveHours: 161, twelveHoursFlag: 0,
      sixteenHours: 161, sixteenHoursFlag: 0,
      twentyFourHours: 174, twentFourHoursFlag: 0,
      fourtyEightHours: 174,
      seventyTwoHours: 174,
      avgIpt: 23.91,
      avgRej: 0.0043,
      templates: [
        ['Gender Detection', 'Model Detection', 'Generic Retouch', 'Model Skin Area', 'Finalize'],
        ['Gender Detection', 'Skin Processing', 'Recreate Details', 'Finalize'],
        ['Preparation', 'Gender Detection', 'Combination', 'Retouch: Garments 1', 'Retouch: Garments 2']
      ]
    },
    {
      name: 'Contrast Against Background',
      pipeline: 0,
      notAssigned: 1,
      assigned: 16,
      longestWaitingTime: '00:02',
      nextDeadline: '11:26',
      sorting: '08:45',
      editors: 1,
      potential: 19,
      forced: 0,
      idle: 0,
      freelancer: 0,
      zeroHours: 0, zeroHoursFlag: 0,
      twoHours: 0, twoHoursFlag: 0,
      fourHours: 0, fourHoursFlag: 0,
      eightHours: 0, eightHoursFlag: 0,
      twelveHours: 161, twelveHoursFlag: 0,
      sixteenHours: 161, sixteenHoursFlag: 0,
      twentyFourHours: 174, twentFourHoursFlag: 0,
      fourtyEightHours: 174,
      seventyTwoHours: 174,
      avgIpt: 39.38,
      avgRej: 0.0041
    },
    {
      name: 'Model Detection',
      pipeline: 0,
      notAssigned: 1,
      assigned: 16,
      longestWaitingTime: '00:02',
      nextDeadline: '11:26',
      sorting: '08:45',
      editors: 1,
      potential: 19,
      forced: 0,
      idle: 0,
      freelancer: 0,
      zeroHours: 0, zeroHoursFlag: 0,
      twoHours: 0, twoHoursFlag: 0,
      fourHours: 0, fourHoursFlag: 0,
      eightHours: 0, eightHoursFlag: 0,
      twelveHours: 161, twelveHoursFlag: 0,
      sixteenHours: 161, sixteenHoursFlag: 0,
      twentyFourHours: 174, twentFourHoursFlag: 0,
      fourtyEightHours: 174,
      seventyTwoHours: 174,
      avgIpt: 11.88,
      avgRej: 0.0012
    },
    {
      name: 'Model Skin Area',
      pipeline: 0,
      notAssigned: 1,
      assigned: 16,
      longestWaitingTime: '00:02',
      nextDeadline: '11:26',
      sorting: '08:45',
      editors: 1,
      potential: 19,
      forced: 0,
      idle: 0,
      freelancer: 0,
      zeroHours: 0, zeroHoursFlag: 0,
      twoHours: 0, twoHoursFlag: 0,
      fourHours: 0, fourHoursFlag: 0,
      eightHours: 0, eightHoursFlag: 0,
      twelveHours: 161, twelveHoursFlag: 0,
      sixteenHours: 161, sixteenHoursFlag: 0,
      twentyFourHours: 174, twentFourHoursFlag: 0,
      fourtyEightHours: 174,
      seventyTwoHours: 174,
      avgIpt: 20.23,
      avgRej: 0.0016
    },
    {
      name: 'Mirror Detection',
      pipeline: 0,
      notAssigned: 1,
      assigned: 16,
      longestWaitingTime: '00:02',
      nextDeadline: '11:26',
      sorting: '08:45',
      editors: 1,
      potential: 19,
      forced: 0,
      idle: 0,
      freelancer: 0,
      zeroHours: 0, zeroHoursFlag: 0,
      twoHours: 0, twoHoursFlag: 0,
      fourHours: 0, fourHoursFlag: 0,
      eightHours: 0, eightHoursFlag: 0,
      twelveHours: 161, twelveHoursFlag: 0,
      sixteenHours: 161, sixteenHoursFlag: 0,
      twentyFourHours: 174, twentFourHoursFlag: 0,
      fourtyEightHours: 174,
      seventyTwoHours: 174,
      avgIpt: 23.14,
      avgRej: 0.0031
    },
    {
      name: 'Hanger Detection',
      pipeline: 0,
      notAssigned: 1,
      assigned: 16,
      longestWaitingTime: '00:02',
      nextDeadline: '11:26',
      sorting: '08:45',
      editors: 1,
      potential: 19,
      forced: 0,
      idle: 0,
      freelancer: 0,
      zeroHours: 0, zeroHoursFlag: 0,
      twoHours: 0, twoHoursFlag: 0,
      fourHours: 0, fourHoursFlag: 0,
      eightHours: 0, eightHoursFlag: 0,
      twelveHours: 161, twelveHoursFlag: 0,
      sixteenHours: 161, sixteenHoursFlag: 0,
      twentyFourHours: 174, twentFourHoursFlag: 0,
      fourtyEightHours: 174,
      seventyTwoHours: 174,
      avgIpt: 15.26,
      avgRej: 0.0008
    },
    {
      name: 'Props Detection',
      pipeline: 0,
      notAssigned: 1,
      assigned: 16,
      longestWaitingTime: '00:02',
      nextDeadline: '11:26',
      sorting: '08:45',
      editors: 1,
      potential: 19,
      forced: 0,
      idle: 0,
      freelancer: 0,
      zeroHours: 0, zeroHoursFlag: 0,
      twoHours: 0, twoHoursFlag: 0,
      fourHours: 0, fourHoursFlag: 0,
      eightHours: 0, eightHoursFlag: 0,
      twelveHours: 161, twelveHoursFlag: 0,
      sixteenHours: 161, sixteenHoursFlag: 0,
      twentyFourHours: 174, twentFourHoursFlag: 0,
      fourtyEightHours: 174,
      seventyTwoHours: 174,
      avgIpt: 29.56,
      avgRej: 0.0028
    },
    {
      name: 'Rotate',
      pipeline: 0,
      notAssigned: 1,
      assigned: 16,
      longestWaitingTime: '00:02',
      nextDeadline: '11:26',
      sorting: '08:45',
      editors: 1,
      potential: 19,
      forced: 0,
      idle: 0,
      freelancer: 0,
      zeroHours: 0, zeroHoursFlag: 0,
      twoHours: 0, twoHoursFlag: 0,
      fourHours: 0, fourHoursFlag: 0,
      eightHours: 0, eightHoursFlag: 0,
      twelveHours: 161, twelveHoursFlag: 0,
      sixteenHours: 161, sixteenHoursFlag: 0,
      twentyFourHours: 174, twentFourHoursFlag: 0,
      fourtyEightHours: 174,
      seventyTwoHours: 174,
      avgIpt: 35.64,
      avgRej: 0.0061
    },
    {
      name: 'Crop & Scale',
      pipeline: 0,
      notAssigned: 1,
      assigned: 16,
      longestWaitingTime: '00:02',
      nextDeadline: '11:26',
      sorting: '08:45',
      editors: 1,
      potential: 19,
      forced: 0,
      idle: 0,
      freelancer: 0,
      zeroHours: 0, zeroHoursFlag: 0,
      twoHours: 0, twoHoursFlag: 0,
      fourHours: 0, fourHoursFlag: 0,
      eightHours: 0, eightHoursFlag: 0,
      twelveHours: 161, twelveHoursFlag: 0,
      sixteenHours: 161, sixteenHoursFlag: 0,
      twentyFourHours: 174, twentFourHoursFlag: 0,
      fourtyEightHours: 174,
      seventyTwoHours: 174,
      avgIpt: 58.80,
      avgRej: 0.0128
    },
    {
      name: 'Preparation',
      pipeline: 0,
      notAssigned: 1,
      assigned: 16,
      longestWaitingTime: '00:02',
      nextDeadline: '11:26',
      sorting: '08:45',
      editors: 1,
      potential: 19,
      forced: 0,
      idle: 0,
      freelancer: 0,
      zeroHours: 0, zeroHoursFlag: 0,
      twoHours: 0, twoHoursFlag: 0,
      fourHours: 0, fourHoursFlag: 0,
      eightHours: 0, eightHoursFlag: 0,
      twelveHours: 161, twelveHoursFlag: 0,
      sixteenHours: 161, sixteenHoursFlag: 0,
      twentyFourHours: 174, twentFourHoursFlag: 0,
      fourtyEightHours: 174,
      seventyTwoHours: 174,
      avgIpt: 177.97,
      avgRej: 0.0488
    },
    {
      name: 'New Preparation',
      pipeline: 0,
      notAssigned: 1,
      assigned: 16,
      longestWaitingTime: '00:02',
      nextDeadline: '11:26',
      sorting: '08:45',
      editors: 1,
      potential: 19,
      forced: 0,
      idle: 0,
      freelancer: 0,
      zeroHours: 0, zeroHoursFlag: 0,
      twoHours: 0, twoHoursFlag: 0,
      fourHours: 0, fourHoursFlag: 0,
      eightHours: 0, eightHoursFlag: 0,
      twelveHours: 161, twelveHoursFlag: 0,
      sixteenHours: 161, sixteenHoursFlag: 0,
      twentyFourHours: 174, twentFourHoursFlag: 0,
      fourtyEightHours: 174,
      seventyTwoHours: 174,
      avgIpt: 116.59,
      avgRej: 0.0455
    },
    {
      name: 'Auto Preparation',
      pipeline: 0,
      notAssigned: 1,
      assigned: 16,
      longestWaitingTime: '00:02',
      nextDeadline: '11:26',
      sorting: '08:45',
      editors: 1,
      potential: 19,
      forced: 0,
      idle: 0,
      freelancer: 0,
      zeroHours: 0, zeroHoursFlag: 0,
      twoHours: 0, twoHoursFlag: 0,
      fourHours: 0, fourHoursFlag: 0,
      eightHours: 0, eightHoursFlag: 0,
      twelveHours: 161, twelveHoursFlag: 0,
      sixteenHours: 161, sixteenHoursFlag: 0,
      twentyFourHours: 174, twentFourHoursFlag: 0,
      fourtyEightHours: 174,
      seventyTwoHours: 174,
      avgIpt: 98.15,
      avgRej: 0.0291
    },
    {
      name: 'Photo Correction',
      pipeline: 0,
      notAssigned: 1,
      assigned: 16,
      longestWaitingTime: '00:02',
      nextDeadline: '11:26',
      sorting: '08:45',
      editors: 1,
      potential: 19,
      forced: 0,
      idle: 0,
      freelancer: 0,
      zeroHours: 0, zeroHoursFlag: 0,
      twoHours: 0, twoHoursFlag: 0,
      fourHours: 0, fourHoursFlag: 0,
      eightHours: 0, eightHoursFlag: 0,
      twelveHours: 161, twelveHoursFlag: 0,
      sixteenHours: 161, sixteenHoursFlag: 0,
      twentyFourHours: 174, twentFourHoursFlag: 0,
      fourtyEightHours: 174,
      seventyTwoHours: 174,
      avgIpt: 198.48,
      avgRej: 0.0434
    },
    {
      name: 'Combination',
      pipeline: 0,
      notAssigned: 1,
      assigned: 16,
      longestWaitingTime: '00:02',
      nextDeadline: '11:26',
      sorting: '08:45',
      editors: 1,
      potential: 19,
      forced: 0,
      idle: 0,
      freelancer: 0,
      zeroHours: 0, zeroHoursFlag: 0,
      twoHours: 0, twoHoursFlag: 0,
      fourHours: 0, fourHoursFlag: 0,
      eightHours: 0, eightHoursFlag: 0,
      twelveHours: 161, twelveHoursFlag: 0,
      sixteenHours: 161, sixteenHoursFlag: 0,
      twentyFourHours: 174, twentFourHoursFlag: 0,
      fourtyEightHours: 174,
      seventyTwoHours: 174,
      avgIpt: 141.91,
      avgRej: 0.0393
    },
    {
      name: 'General Retouch',
      pipeline: 0,
      notAssigned: 1,
      assigned: 16,
      longestWaitingTime: '00:02',
      nextDeadline: '11:26',
      sorting: '08:45',
      editors: 1,
      potential: 19,
      forced: 0,
      idle: 0,
      freelancer: 0,
      zeroHours: 0, zeroHoursFlag: 0,
      twoHours: 0, twoHoursFlag: 0,
      fourHours: 0, fourHoursFlag: 0,
      eightHours: 0, eightHoursFlag: 0,
      twelveHours: 161, twelveHoursFlag: 0,
      sixteenHours: 161, sixteenHoursFlag: 0,
      twentyFourHours: 174, twentFourHoursFlag: 0,
      fourtyEightHours: 174,
      seventyTwoHours: 174,
      avgIpt: 158.34,
      avgRej: 0.0434
    },
    {
      name: 'Recreate Details',
      pipeline: 0,
      notAssigned: 1,
      assigned: 16,
      longestWaitingTime: '00:02',
      nextDeadline: '11:26',
      sorting: '08:45',
      editors: 1,
      potential: 19,
      forced: 0,
      idle: 0,
      freelancer: 0,
      zeroHours: 0, zeroHoursFlag: 0,
      twoHours: 0, twoHoursFlag: 0,
      fourHours: 0, fourHoursFlag: 0,
      eightHours: 0, eightHoursFlag: 0,
      twelveHours: 161, twelveHoursFlag: 0,
      sixteenHours: 161, sixteenHoursFlag: 0,
      twentyFourHours: 174, twentFourHoursFlag: 0,
      fourtyEightHours: 174,
      seventyTwoHours: 174,
      avgIpt: 144.46,
      avgRej: 0.0513
    },
    {
      name: 'Retouch: Shape',
      pipeline: 0,
      notAssigned: 1,
      assigned: 16,
      longestWaitingTime: '00:02',
      nextDeadline: '11:26',
      sorting: '08:45',
      editors: 1,
      potential: 19,
      forced: 0,
      idle: 0,
      freelancer: 0,
      zeroHours: 0, zeroHoursFlag: 0,
      twoHours: 0, twoHoursFlag: 0,
      fourHours: 0, fourHoursFlag: 0,
      eightHours: 0, eightHoursFlag: 0,
      twelveHours: 161, twelveHoursFlag: 0,
      sixteenHours: 161, sixteenHoursFlag: 0,
      twentyFourHours: 174, twentFourHoursFlag: 0,
      fourtyEightHours: 174,
      seventyTwoHours: 174,
      avgIpt: 163.71,
      avgRej: 0.0460
    },
    {
      name: 'Generic Retouch',
      pipeline: 0,
      notAssigned: 1,
      assigned: 16,
      longestWaitingTime: '00:02',
      nextDeadline: '11:26',
      sorting: '08:45',
      editors: 1,
      potential: 19,
      forced: 0,
      idle: 0,
      freelancer: 0,
      zeroHours: 0, zeroHoursFlag: 0,
      twoHours: 0, twoHoursFlag: 0,
      fourHours: 0, fourHoursFlag: 0,
      eightHours: 0, eightHoursFlag: 0,
      twelveHours: 161, twelveHoursFlag: 0,
      sixteenHours: 161, sixteenHoursFlag: 0,
      twentyFourHours: 174, twentFourHoursFlag: 0,
      fourtyEightHours: 174,
      seventyTwoHours: 174,
      avgIpt: 152.55,
      avgRej: 0.0552
    },
    {
      name: 'Retouch: 3D',
      pipeline: 0,
      notAssigned: 1,
      assigned: 16,
      longestWaitingTime: '00:02',
      nextDeadline: '11:26',
      sorting: '08:45',
      editors: 1,
      potential: 19,
      forced: 0,
      idle: 0,
      freelancer: 0,
      zeroHours: 0, zeroHoursFlag: 0,
      twoHours: 0, twoHoursFlag: 0,
      fourHours: 0, fourHoursFlag: 0,
      eightHours: 0, eightHoursFlag: 0,
      twelveHours: 161, twelveHoursFlag: 0,
      sixteenHours: 161, sixteenHoursFlag: 0,
      twentyFourHours: 174, twentFourHoursFlag: 0,
      fourtyEightHours: 174,
      seventyTwoHours: 174,
      avgIpt: 236.45,
      avgRej: 0.0580
    },
    {
      name: 'Retouch: Garments 1',
      pipeline: 0,
      notAssigned: 1,
      assigned: 16,
      longestWaitingTime: '00:02',
      nextDeadline: '11:26',
      sorting: '08:45',
      editors: 1,
      potential: 19,
      forced: 0,
      idle: 0,
      freelancer: 0,
      zeroHours: 0, zeroHoursFlag: 0,
      twoHours: 0, twoHoursFlag: 0,
      fourHours: 0, fourHoursFlag: 0,
      eightHours: 0, eightHoursFlag: 0,
      twelveHours: 161, twelveHoursFlag: 0,
      sixteenHours: 161, sixteenHoursFlag: 0,
      twentyFourHours: 174, twentFourHoursFlag: 0,
      fourtyEightHours: 174,
      seventyTwoHours: 174,
      avgIpt: 134.29,
      avgRej: 0.0421
    },
    {
      name: 'Retouch: Garments 2',
      pipeline: 0,
      notAssigned: 1,
      assigned: 16,
      longestWaitingTime: '00:02',
      nextDeadline: '11:26',
      sorting: '08:45',
      editors: 1,
      potential: 19,
      forced: 0,
      idle: 0,
      freelancer: 0,
      zeroHours: 0, zeroHoursFlag: 0,
      twoHours: 0, twoHoursFlag: 0,
      fourHours: 0, fourHoursFlag: 0,
      eightHours: 0, eightHoursFlag: 0,
      twelveHours: 161, twelveHoursFlag: 0,
      sixteenHours: 161, sixteenHoursFlag: 0,
      twentyFourHours: 174, twentFourHoursFlag: 0,
      fourtyEightHours: 174,
      seventyTwoHours: 174,
      avgIpt: 143.65,
      avgRej: 0.0487
    },
    {
      name: 'Retouch: Garments 3',
      pipeline: 0,
      notAssigned: 1,
      assigned: 16,
      longestWaitingTime: '00:02',
      nextDeadline: '11:26',
      sorting: '08:45',
      editors: 1,
      potential: 19,
      forced: 0,
      idle: 0,
      freelancer: 0,
      zeroHours: 0, zeroHoursFlag: 0,
      twoHours: 0, twoHoursFlag: 0,
      fourHours: 0, fourHoursFlag: 0,
      eightHours: 0, eightHoursFlag: 0,
      twelveHours: 161, twelveHoursFlag: 0,
      sixteenHours: 161, sixteenHoursFlag: 0,
      twentyFourHours: 174, twentFourHoursFlag: 0,
      fourtyEightHours: 174,
      seventyTwoHours: 174,
      avgIpt: 208.92,
      avgRej: 0.0695
    },
    {
      name: 'Retouch: Footwear',
      pipeline: 0,
      notAssigned: 1,
      assigned: 16,
      longestWaitingTime: '00:02',
      nextDeadline: '11:26',
      sorting: '08:45',
      editors: 1,
      potential: 19,
      forced: 0,
      idle: 0,
      freelancer: 0,
      zeroHours: 0, zeroHoursFlag: 0,
      twoHours: 0, twoHoursFlag: 0,
      fourHours: 0, fourHoursFlag: 0,
      eightHours: 0, eightHoursFlag: 0,
      twelveHours: 161, twelveHoursFlag: 0,
      sixteenHours: 161, sixteenHoursFlag: 0,
      twentyFourHours: 174, twentFourHoursFlag: 0,
      fourtyEightHours: 174,
      seventyTwoHours: 174,
      avgIpt: 231.28,
      avgRej: 0.0509
    },
    {
      name: 'Retouch: Jewelry',
      pipeline: 0,
      notAssigned: 1,
      assigned: 16,
      longestWaitingTime: '00:02',
      nextDeadline: '11:26',
      sorting: '08:45',
      editors: 1,
      potential: 19,
      forced: 0,
      idle: 0,
      freelancer: 0,
      zeroHours: 0, zeroHoursFlag: 0,
      twoHours: 0, twoHoursFlag: 0,
      fourHours: 0, fourHoursFlag: 0,
      eightHours: 0, eightHoursFlag: 0,
      twelveHours: 161, twelveHoursFlag: 0,
      sixteenHours: 161, sixteenHoursFlag: 0,
      twentyFourHours: 174, twentFourHoursFlag: 0,
      fourtyEightHours: 174,
      seventyTwoHours: 174,
      avgIpt: 186.33,
      avgRej: 0.0743
    },
    {
      name: 'Retouch: Furniture',
      pipeline: 0,
      notAssigned: 1,
      assigned: 16,
      longestWaitingTime: '00:02',
      nextDeadline: '11:26',
      sorting: '08:45',
      editors: 1,
      potential: 19,
      forced: 0,
      idle: 0,
      freelancer: 0,
      zeroHours: 0, zeroHoursFlag: 0,
      twoHours: 0, twoHoursFlag: 0,
      fourHours: 0, fourHoursFlag: 0,
      eightHours: 0, eightHoursFlag: 0,
      twelveHours: 161, twelveHoursFlag: 0,
      sixteenHours: 161, sixteenHoursFlag: 0,
      twentyFourHours: 174, twentFourHoursFlag: 0,
      fourtyEightHours: 174,
      seventyTwoHours: 174,
      avgIpt: 170.99,
      avgRej: 0.0426
    },
    {
      name: 'Retouch: Accessories',
      pipeline: 0,
      notAssigned: 1,
      assigned: 16,
      longestWaitingTime: '00:02',
      nextDeadline: '11:26',
      sorting: '08:45',
      editors: 1,
      potential: 19,
      forced: 0,
      idle: 0,
      freelancer: 0,
      zeroHours: 0, zeroHoursFlag: 0,
      twoHours: 0, twoHoursFlag: 0,
      fourHours: 0, fourHoursFlag: 0,
      eightHours: 0, eightHoursFlag: 0,
      twelveHours: 161, twelveHoursFlag: 0,
      sixteenHours: 161, sixteenHoursFlag: 0,
      twentyFourHours: 174, twentFourHoursFlag: 0,
      fourtyEightHours: 174,
      seventyTwoHours: 174,
      avgIpt: 145.60,
      avgRej: 0.0418
    },
    {
      name: 'Retouch: Cosmetics',
      pipeline: 0,
      notAssigned: 1,
      assigned: 16,
      longestWaitingTime: '00:02',
      nextDeadline: '11:26',
      sorting: '08:45',
      editors: 1,
      potential: 19,
      forced: 0,
      idle: 0,
      freelancer: 0,
      zeroHours: 0, zeroHoursFlag: 0,
      twoHours: 0, twoHoursFlag: 0,
      fourHours: 0, fourHoursFlag: 0,
      eightHours: 0, eightHoursFlag: 0,
      twelveHours: 161, twelveHoursFlag: 0,
      sixteenHours: 161, sixteenHoursFlag: 0,
      twentyFourHours: 174, twentFourHoursFlag: 0,
      fourtyEightHours: 174,
      seventyTwoHours: 174,
      avgIpt: 172.92,
      avgRej: 0.0544
    },
    {
      name: 'Retouch: Model',
      pipeline: 0,
      notAssigned: 1,
      assigned: 16,
      longestWaitingTime: '00:02',
      nextDeadline: '11:26',
      sorting: '08:45',
      editors: 1,
      potential: 19,
      forced: 0,
      idle: 0,
      freelancer: 0,
      zeroHours: 0, zeroHoursFlag: 0,
      twoHours: 0, twoHoursFlag: 0,
      fourHours: 0, fourHoursFlag: 0,
      eightHours: 0, eightHoursFlag: 0,
      twelveHours: 161, twelveHoursFlag: 0,
      sixteenHours: 161, sixteenHoursFlag: 0,
      twentyFourHours: 174, twentFourHoursFlag: 0,
      fourtyEightHours: 174,
      seventyTwoHours: 174,
      avgIpt: 150.48,
      avgRej: 0.0456
    },
    {
      name: 'Retouch: Model Advanced',
      pipeline: 0,
      notAssigned: 1,
      assigned: 16,
      longestWaitingTime: '00:02',
      nextDeadline: '11:26',
      sorting: '08:45',
      editors: 1,
      potential: 19,
      forced: 0,
      idle: 0,
      freelancer: 0,
      zeroHours: 0, zeroHoursFlag: 0,
      twoHours: 0, twoHoursFlag: 0,
      fourHours: 0, fourHoursFlag: 0,
      eightHours: 0, eightHoursFlag: 0,
      twelveHours: 161, twelveHoursFlag: 0,
      sixteenHours: 161, sixteenHoursFlag: 0,
      twentyFourHours: 174, twentFourHoursFlag: 0,
      fourtyEightHours: 174,
      seventyTwoHours: 174,
      avgIpt: 27,
      avgRej: 0.0000
    },
    {
      name: 'Retouch: Skin Processing',
      pipeline: 0,
      notAssigned: 1,
      assigned: 16,
      longestWaitingTime: '00:02',
      nextDeadline: '11:26',
      sorting: '08:45',
      editors: 1,
      potential: 19,
      forced: 0,
      idle: 0,
      freelancer: 0,
      zeroHours: 0, zeroHoursFlag: 0,
      twoHours: 0, twoHoursFlag: 0,
      fourHours: 0, fourHoursFlag: 0,
      eightHours: 0, eightHoursFlag: 0,
      twelveHours: 161, twelveHoursFlag: 0,
      sixteenHours: 161, sixteenHoursFlag: 0,
      twentyFourHours: 174, twentFourHoursFlag: 0,
      fourtyEightHours: 174,
      seventyTwoHours: 174,
      avgIpt: 184.38,
      avgRej: 0.0733
    },
    {
      name: 'Qualification',
      pipeline: 0,
      notAssigned: 1,
      assigned: 16,
      longestWaitingTime: '00:02',
      nextDeadline: '11:26',
      sorting: '08:45',
      editors: 1,
      potential: 19,
      forced: 0,
      idle: 0,
      freelancer: 0,
      zeroHours: 0, zeroHoursFlag: 0,
      twoHours: 0, twoHoursFlag: 0,
      fourHours: 0, fourHoursFlag: 0,
      eightHours: 0, eightHoursFlag: 0,
      twelveHours: 161, twelveHoursFlag: 0,
      sixteenHours: 161, sixteenHoursFlag: 0,
      twentyFourHours: 174, twentFourHoursFlag: 0,
      fourtyEightHours: 174,
      seventyTwoHours: 174,
      avgIpt: 264.29,
      avgRej: 0.0901
    },
    {
      name: 'Preparation for Colorways',
      pipeline: 0,
      notAssigned: 1,
      assigned: 16,
      longestWaitingTime: '00:02',
      nextDeadline: '11:26',
      sorting: '08:45',
      editors: 1,
      potential: 19,
      forced: 0,
      idle: 0,
      freelancer: 0,
      zeroHours: 0, zeroHoursFlag: 0,
      twoHours: 0, twoHoursFlag: 0,
      fourHours: 0, fourHoursFlag: 0,
      eightHours: 0, eightHoursFlag: 0,
      twelveHours: 161, twelveHoursFlag: 0,
      sixteenHours: 161, sixteenHoursFlag: 0,
      twentyFourHours: 174, twentFourHoursFlag: 0,
      fourtyEightHours: 174,
      seventyTwoHours: 174,
      avgIpt: 107.00,
      avgRej: 0.0435
    },
    {
      name: 'Texture Replacement',
      pipeline: 0,
      notAssigned: 1,
      assigned: 16,
      longestWaitingTime: '00:02',
      nextDeadline: '11:26',
      sorting: '08:45',
      editors: 1,
      potential: 19,
      forced: 0,
      idle: 0,
      freelancer: 0,
      zeroHours: 0, zeroHoursFlag: 0,
      twoHours: 0, twoHoursFlag: 0,
      fourHours: 0, fourHoursFlag: 0,
      eightHours: 0, eightHoursFlag: 0,
      twelveHours: 161, twelveHoursFlag: 0,
      sixteenHours: 161, sixteenHoursFlag: 0,
      twentyFourHours: 174, twentFourHoursFlag: 0,
      fourtyEightHours: 174,
      seventyTwoHours: 174,
      avgIpt: 458.56,
      avgRej: 0.0471
    },
    {
      name: 'Color Change',
      pipeline: 0,
      notAssigned: 1,
      assigned: 16,
      longestWaitingTime: '00:02',
      nextDeadline: '11:26',
      sorting: '08:45',
      editors: 1,
      potential: 19,
      forced: 0,
      idle: 0,
      freelancer: 0,
      zeroHours: 0, zeroHoursFlag: 0,
      twoHours: 0, twoHoursFlag: 0,
      fourHours: 0, fourHoursFlag: 0,
      eightHours: 0, eightHoursFlag: 0,
      twelveHours: 161, twelveHoursFlag: 0,
      sixteenHours: 161, sixteenHoursFlag: 0,
      twentyFourHours: 174, twentFourHoursFlag: 0,
      fourtyEightHours: 174,
      seventyTwoHours: 174,
      avgIpt: 312.52,
      avgRej: 0.0801
    },
    {
      name: 'Dobby',
      pipeline: 0,
      notAssigned: 1,
      assigned: 16,
      longestWaitingTime: '00:02',
      nextDeadline: '11:26',
      sorting: '08:45',
      editors: 1,
      potential: 19,
      forced: 0,
      idle: 0,
      freelancer: 0,
      zeroHours: 0, zeroHoursFlag: 0,
      twoHours: 0, twoHoursFlag: 0,
      fourHours: 0, fourHoursFlag: 0,
      eightHours: 0, eightHoursFlag: 0,
      twelveHours: 161, twelveHoursFlag: 0,
      sixteenHours: 161, sixteenHoursFlag: 0,
      twentyFourHours: 174, twentFourHoursFlag: 0,
      fourtyEightHours: 174,
      seventyTwoHours: 174,
      avgIpt: 389.64,
      avgRej: 0.1338
    },
    {
      name: 'New Path',
      pipeline: 0,
      notAssigned: 1,
      assigned: 16,
      longestWaitingTime: '00:02',
      nextDeadline: '11:26',
      sorting: '08:45',
      editors: 1,
      potential: 19,
      forced: 0,
      idle: 0,
      freelancer: 0,
      zeroHours: 0, zeroHoursFlag: 0,
      twoHours: 0, twoHoursFlag: 0,
      fourHours: 0, fourHoursFlag: 0,
      eightHours: 0, eightHoursFlag: 0,
      twelveHours: 161, twelveHoursFlag: 0,
      sixteenHours: 161, sixteenHoursFlag: 0,
      twentyFourHours: 174, twentFourHoursFlag: 0,
      fourtyEightHours: 174,
      seventyTwoHours: 174,
      avgIpt: 336.57,
      avgRej: 0.0635
    },
    {
      name: 'Apply Path',
      pipeline: 0,
      notAssigned: 1,
      assigned: 16,
      longestWaitingTime: '00:02',
      nextDeadline: '11:26',
      sorting: '08:45',
      editors: 1,
      potential: 19,
      forced: 0,
      idle: 0,
      freelancer: 0,
      zeroHours: 0, zeroHoursFlag: 0,
      twoHours: 0, twoHoursFlag: 0,
      fourHours: 0, fourHoursFlag: 0,
      eightHours: 0, eightHoursFlag: 0,
      twelveHours: 161, twelveHoursFlag: 0,
      sixteenHours: 161, sixteenHoursFlag: 0,
      twentyFourHours: 174, twentFourHoursFlag: 0,
      fourtyEightHours: 174,
      seventyTwoHours: 174,
      avgIpt: 63.06,
      avgRej: 0.0241
    },
    {
      name: 'Advanced Path',
      pipeline: 0,
      notAssigned: 1,
      assigned: 16,
      longestWaitingTime: '00:02',
      nextDeadline: '11:26',
      sorting: '08:45',
      editors: 1,
      potential: 19,
      forced: 0,
      idle: 0,
      freelancer: 0,
      zeroHours: 0, zeroHoursFlag: 0,
      twoHours: 0, twoHoursFlag: 0,
      fourHours: 0, fourHoursFlag: 0,
      eightHours: 0, eightHoursFlag: 0,
      twelveHours: 161, twelveHoursFlag: 0,
      sixteenHours: 161, sixteenHoursFlag: 0,
      twentyFourHours: 174, twentFourHoursFlag: 0,
      fourtyEightHours: 174,
      seventyTwoHours: 174,
      avgIpt: 231.52,
      avgRej: 0.0660
    },
    {
      name: 'Trimap',
      pipeline: 0,
      notAssigned: 1,
      assigned: 16,
      longestWaitingTime: '00:02',
      nextDeadline: '11:26',
      sorting: '08:45',
      editors: 1,
      potential: 19,
      forced: 0,
      idle: 0,
      freelancer: 0,
      zeroHours: 0, zeroHoursFlag: 0,
      twoHours: 0, twoHoursFlag: 0,
      fourHours: 0, fourHoursFlag: 0,
      eightHours: 0, eightHoursFlag: 0,
      twelveHours: 161, twelveHoursFlag: 0,
      sixteenHours: 161, sixteenHoursFlag: 0,
      twentyFourHours: 174, twentFourHoursFlag: 0,
      fourtyEightHours: 174,
      seventyTwoHours: 174,
      avgIpt: 92.42,
      avgRej: 0.0194
    },
    {
      name: 'New Layer Mask',
      pipeline: 0,
      notAssigned: 1,
      assigned: 16,
      longestWaitingTime: '00:02',
      nextDeadline: '11:26',
      sorting: '08:45',
      editors: 1,
      potential: 19,
      forced: 0,
      idle: 0,
      freelancer: 0,
      zeroHours: 0, zeroHoursFlag: 0,
      twoHours: 0, twoHoursFlag: 0,
      fourHours: 0, fourHoursFlag: 0,
      eightHours: 0, eightHoursFlag: 0,
      twelveHours: 161, twelveHoursFlag: 0,
      sixteenHours: 161, sixteenHoursFlag: 0,
      twentyFourHours: 174, twentFourHoursFlag: 0,
      fourtyEightHours: 174,
      seventyTwoHours: 174,
      avgIpt: 336.57,
      avgRej: 0.0635
    },
    {
      name: 'AI Mask',
      pipeline: 0,
      notAssigned: 1,
      assigned: 16,
      longestWaitingTime: '00:02',
      nextDeadline: '11:26',
      sorting: '08:45',
      editors: 1,
      potential: 19,
      forced: 0,
      idle: 0,
      freelancer: 0,
      zeroHours: 0, zeroHoursFlag: 0,
      twoHours: 0, twoHoursFlag: 0,
      fourHours: 0, fourHoursFlag: 0,
      eightHours: 0, eightHoursFlag: 0,
      twelveHours: 161, twelveHoursFlag: 0,
      sixteenHours: 161, sixteenHoursFlag: 0,
      twentyFourHours: 174, twentFourHoursFlag: 0,
      fourtyEightHours: 174,
      seventyTwoHours: 174,
      avgIpt: 266.30,
      avgRej: 0.0621
    },
    {
      name: 'Apply Layer Mask',
      pipeline: 0,
      notAssigned: 1,
      assigned: 16,
      longestWaitingTime: '00:02',
      nextDeadline: '11:26',
      sorting: '08:45',
      editors: 1,
      potential: 19,
      forced: 0,
      idle: 0,
      freelancer: 0,
      zeroHours: 0, zeroHoursFlag: 0,
      twoHours: 0, twoHoursFlag: 0,
      fourHours: 0, fourHoursFlag: 0,
      eightHours: 0, eightHoursFlag: 0,
      twelveHours: 161, twelveHoursFlag: 0,
      sixteenHours: 161, sixteenHoursFlag: 0,
      twentyFourHours: 174, twentFourHoursFlag: 0,
      fourtyEightHours: 174,
      seventyTwoHours: 174,
      avgIpt: 124.03,
      avgRej: 0.0332
    },
    {
      name: 'Path & Mask',
      pipeline: 0,
      notAssigned: 1,
      assigned: 16,
      longestWaitingTime: '00:02',
      nextDeadline: '11:26',
      sorting: '08:45',
      editors: 1,
      potential: 19,
      forced: 0,
      idle: 0,
      freelancer: 0,
      zeroHours: 0, zeroHoursFlag: 0,
      twoHours: 0, twoHoursFlag: 0,
      fourHours: 0, fourHoursFlag: 0,
      eightHours: 0, eightHoursFlag: 0,
      twelveHours: 161, twelveHoursFlag: 0,
      sixteenHours: 161, sixteenHoursFlag: 0,
      twentyFourHours: 174, twentFourHoursFlag: 0,
      fourtyEightHours: 174,
      seventyTwoHours: 174,
      avgIpt: 283.19,
      avgRej: 0.0644
    },
    {
      name: 'Apply Path & Mask',
      pipeline: 0,
      notAssigned: 1,
      assigned: 16,
      longestWaitingTime: '00:02',
      nextDeadline: '11:26',
      sorting: '08:45',
      editors: 1,
      potential: 19,
      forced: 0,
      idle: 0,
      freelancer: 0,
      zeroHours: 0, zeroHoursFlag: 0,
      twoHours: 0, twoHoursFlag: 0,
      fourHours: 0, fourHoursFlag: 0,
      eightHours: 0, eightHoursFlag: 0,
      twelveHours: 161, twelveHoursFlag: 0,
      sixteenHours: 161, sixteenHoursFlag: 0,
      twentyFourHours: 174, twentFourHoursFlag: 0,
      fourtyEightHours: 174,
      seventyTwoHours: 174,
      avgIpt: 128.11,
      avgRej: 0.0309
    },
    {
      name: 'Advanced Mask',
      pipeline: 0,
      notAssigned: 1,
      assigned: 16,
      longestWaitingTime: '00:02',
      nextDeadline: '11:26',
      sorting: '08:45',
      editors: 1,
      potential: 19,
      forced: 0,
      idle: 0,
      freelancer: 0,
      zeroHours: 0, zeroHoursFlag: 0,
      twoHours: 0, twoHoursFlag: 0,
      fourHours: 0, fourHoursFlag: 0,
      eightHours: 0, eightHoursFlag: 0,
      twelveHours: 161, twelveHoursFlag: 0,
      sixteenHours: 161, sixteenHoursFlag: 0,
      twentyFourHours: 174, twentFourHoursFlag: 0,
      fourtyEightHours: 174,
      seventyTwoHours: 174,
      avgIpt: 219.50,
      avgRej: 0.0734
    },
    {
      name: 'Color Adjustment',
      pipeline: 0,
      notAssigned: 1,
      assigned: 16,
      longestWaitingTime: '00:02',
      nextDeadline: '11:26',
      sorting: '08:45',
      editors: 1,
      potential: 19,
      forced: 0,
      idle: 0,
      freelancer: 0,
      zeroHours: 0, zeroHoursFlag: 0,
      twoHours: 0, twoHoursFlag: 0,
      fourHours: 0, fourHoursFlag: 0,
      eightHours: 0, eightHoursFlag: 0,
      twelveHours: 161, twelveHoursFlag: 0,
      sixteenHours: 161, sixteenHoursFlag: 0,
      twentyFourHours: 174, twentFourHoursFlag: 0,
      fourtyEightHours: 174,
      seventyTwoHours: 174,
      avgIpt: 191.20,
      avgRej: 0.0678
    },
    {
      name: 'Background Retouch',
      pipeline: 0,
      notAssigned: 1,
      assigned: 16,
      longestWaitingTime: '00:02',
      nextDeadline: '11:26',
      sorting: '08:45',
      editors: 1,
      potential: 19,
      forced: 0,
      idle: 0,
      freelancer: 0,
      zeroHours: 0, zeroHoursFlag: 0,
      twoHours: 0, twoHoursFlag: 0,
      fourHours: 0, fourHoursFlag: 0,
      eightHours: 0, eightHoursFlag: 0,
      twelveHours: 161, twelveHoursFlag: 0,
      sixteenHours: 161, sixteenHoursFlag: 0,
      twentyFourHours: 174, twentFourHoursFlag: 0,
      fourtyEightHours: 174,
      seventyTwoHours: 174,
      avgIpt: 193.40,
      avgRej: 0.0697
    },
    {
      name: 'Dumbledore',
      pipeline: 0,
      notAssigned: 1,
      assigned: 16,
      longestWaitingTime: '00:02',
      nextDeadline: '11:26',
      sorting: '08:45',
      editors: 1,
      potential: 19,
      forced: 0,
      idle: 0,
      freelancer: 0,
      zeroHours: 0, zeroHoursFlag: 0,
      twoHours: 0, twoHoursFlag: 0,
      fourHours: 0, fourHoursFlag: 0,
      eightHours: 0, eightHoursFlag: 0,
      twelveHours: 161, twelveHoursFlag: 0,
      sixteenHours: 161, sixteenHoursFlag: 0,
      twentyFourHours: 174, twentFourHoursFlag: 0,
      fourtyEightHours: 174,
      seventyTwoHours: 174,
      avgIpt: 182.47,
      avgRej: 0.0546
    },
    {
      name: 'Snape',
      pipeline: 0,
      notAssigned: 1,
      assigned: 16,
      longestWaitingTime: '00:02',
      nextDeadline: '11:26',
      sorting: '08:45',
      editors: 1,
      potential: 19,
      forced: 0,
      idle: 0,
      freelancer: 0,
      zeroHours: 0, zeroHoursFlag: 0,
      twoHours: 0, twoHoursFlag: 0,
      fourHours: 0, fourHoursFlag: 0,
      eightHours: 0, eightHoursFlag: 0,
      twelveHours: 161, twelveHoursFlag: 0,
      sixteenHours: 161, sixteenHoursFlag: 0,
      twentyFourHours: 174, twentFourHoursFlag: 0,
      fourtyEightHours: 174,
      seventyTwoHours: 174,
      avgIpt: 173.51,
      avgRej: 0.0505
    },
    {
      name: 'Stack',
      pipeline: 0,
      notAssigned: 1,
      assigned: 16,
      longestWaitingTime: '00:02',
      nextDeadline: '11:26',
      sorting: '08:45',
      editors: 1,
      potential: 19,
      forced: 0,
      idle: 0,
      freelancer: 0,
      zeroHours: 0, zeroHoursFlag: 0,
      twoHours: 0, twoHoursFlag: 0,
      fourHours: 0, fourHoursFlag: 0,
      eightHours: 0, eightHoursFlag: 0,
      twelveHours: 161, twelveHoursFlag: 0,
      sixteenHours: 161, sixteenHoursFlag: 0,
      twentyFourHours: 174, twentFourHoursFlag: 0,
      fourtyEightHours: 174,
      seventyTwoHours: 174,
      avgIpt: 105.32,
      avgRej: 0.0190
    },
    {
      name: 'VPE Auto Stencil',
      pipeline: 0,
      notAssigned: 1,
      assigned: 16,
      longestWaitingTime: '00:02',
      nextDeadline: '11:26',
      sorting: '08:45',
      editors: 1,
      potential: 19,
      forced: 0,
      idle: 0,
      freelancer: 0,
      zeroHours: 0, zeroHoursFlag: 0,
      twoHours: 0, twoHoursFlag: 0,
      fourHours: 0, fourHoursFlag: 0,
      eightHours: 0, eightHoursFlag: 0,
      twelveHours: 161, twelveHoursFlag: 0,
      sixteenHours: 161, sixteenHoursFlag: 0,
      twentyFourHours: 174, twentFourHoursFlag: 0,
      fourtyEightHours: 174,
      seventyTwoHours: 174,
      avgIpt: 123.28,
      avgRej: 0.0394
    },
    {
      name: 'Auto Stencil',
      pipeline: 0,
      notAssigned: 1,
      assigned: 16,
      longestWaitingTime: '00:02',
      nextDeadline: '11:26',
      sorting: '08:45',
      editors: 1,
      potential: 19,
      forced: 0,
      idle: 0,
      freelancer: 0,
      zeroHours: 0, zeroHoursFlag: 0,
      twoHours: 0, twoHoursFlag: 0,
      fourHours: 0, fourHoursFlag: 0,
      eightHours: 0, eightHoursFlag: 0,
      twelveHours: 161, twelveHoursFlag: 0,
      sixteenHours: 161, sixteenHoursFlag: 0,
      twentyFourHours: 174, twentFourHoursFlag: 0,
      fourtyEightHours: 174,
      seventyTwoHours: 174,
      avgIpt: 160.48,
      avgRej: 0.0478
    },
    {
      name: 'Stencil Manual',
      pipeline: 0,
      notAssigned: 1,
      assigned: 16,
      longestWaitingTime: '00:02',
      nextDeadline: '11:26',
      sorting: '08:45',
      editors: 1,
      potential: 19,
      forced: 0,
      idle: 0,
      freelancer: 0,
      zeroHours: 0, zeroHoursFlag: 0,
      twoHours: 0, twoHoursFlag: 0,
      fourHours: 0, fourHoursFlag: 0,
      eightHours: 0, eightHoursFlag: 0,
      twelveHours: 161, twelveHoursFlag: 0,
      sixteenHours: 161, sixteenHoursFlag: 0,
      twentyFourHours: 174, twentFourHoursFlag: 0,
      fourtyEightHours: 174,
      seventyTwoHours: 174,
      avgIpt: 191.93,
      avgRej: 0.0520
    },
    {
      name: 'Background Extension',
      pipeline: 0,
      notAssigned: 1,
      assigned: 16,
      longestWaitingTime: '00:02',
      nextDeadline: '11:26',
      sorting: '08:45',
      editors: 1,
      potential: 19,
      forced: 0,
      idle: 0,
      freelancer: 0,
      zeroHours: 0, zeroHoursFlag: 0,
      twoHours: 0, twoHoursFlag: 0,
      fourHours: 0, fourHoursFlag: 0,
      eightHours: 0, eightHoursFlag: 0,
      twelveHours: 161, twelveHoursFlag: 0,
      sixteenHours: 161, sixteenHoursFlag: 0,
      twentyFourHours: 174, twentFourHoursFlag: 0,
      fourtyEightHours: 174,
      seventyTwoHours: 174,
      avgIpt: 166.90,
      avgRej: 0.0633
    },
    {
      name: 'Replace Object',
      pipeline: 0,
      notAssigned: 1,
      assigned: 16,
      longestWaitingTime: '00:02',
      nextDeadline: '11:26',
      sorting: '08:45',
      editors: 1,
      potential: 19,
      forced: 0,
      idle: 0,
      freelancer: 0,
      zeroHours: 0, zeroHoursFlag: 0,
      twoHours: 0, twoHoursFlag: 0,
      fourHours: 0, fourHoursFlag: 0,
      eightHours: 0, eightHoursFlag: 0,
      twelveHours: 161, twelveHoursFlag: 0,
      sixteenHours: 161, sixteenHoursFlag: 0,
      twentyFourHours: 174, twentFourHoursFlag: 0,
      fourtyEightHours: 174,
      seventyTwoHours: 174,
      avgIpt: 83.06,
      avgRej: 0.0724
    },
    {
      name: 'Shadow: Drop',
      pipeline: 0,
      notAssigned: 1,
      assigned: 16,
      longestWaitingTime: '00:02',
      nextDeadline: '11:26',
      sorting: '08:45',
      editors: 1,
      potential: 19,
      forced: 0,
      idle: 0,
      freelancer: 0,
      zeroHours: 0, zeroHoursFlag: 0,
      twoHours: 0, twoHoursFlag: 0,
      fourHours: 0, fourHoursFlag: 0,
      eightHours: 0, eightHoursFlag: 0,
      twelveHours: 161, twelveHoursFlag: 0,
      sixteenHours: 161, sixteenHoursFlag: 0,
      twentyFourHours: 174, twentFourHoursFlag: 0,
      fourtyEightHours: 174,
      seventyTwoHours: 174,
      avgIpt: 142.31,
      avgRej: 0.0459
    },
    {
      name: 'Shadow: Reflection',
      pipeline: 0,
      notAssigned: 1,
      assigned: 16,
      longestWaitingTime: '00:02',
      nextDeadline: '11:26',
      sorting: '08:45',
      editors: 1,
      potential: 19,
      forced: 0,
      idle: 0,
      freelancer: 0,
      zeroHours: 0, zeroHoursFlag: 0,
      twoHours: 0, twoHoursFlag: 0,
      fourHours: 0, fourHoursFlag: 0,
      eightHours: 0, eightHoursFlag: 0,
      twelveHours: 161, twelveHoursFlag: 0,
      sixteenHours: 161, sixteenHoursFlag: 0,
      twentyFourHours: 174, twentFourHoursFlag: 0,
      fourtyEightHours: 174,
      seventyTwoHours: 174,
      avgIpt: 226.72,
      avgRej: 0.0489
    },
    {
      name: 'Shadow: Natural',
      pipeline: 0,
      notAssigned: 1,
      assigned: 16,
      longestWaitingTime: '00:02',
      nextDeadline: '11:26',
      sorting: '08:45',
      editors: 1,
      potential: 19,
      forced: 0,
      idle: 0,
      freelancer: 0,
      zeroHours: 0, zeroHoursFlag: 0,
      twoHours: 0, twoHoursFlag: 0,
      fourHours: 0, fourHoursFlag: 0,
      eightHours: 0, eightHoursFlag: 0,
      twelveHours: 161, twelveHoursFlag: 0,
      sixteenHours: 161, sixteenHoursFlag: 0,
      twentyFourHours: 174, twentFourHoursFlag: 0,
      fourtyEightHours: 174,
      seventyTwoHours: 174,
      avgIpt: 154.57,
      avgRej: 0.0489
    },
    {
      name: 'Shadow: Cast',
      pipeline: 0,
      notAssigned: 1,
      assigned: 16,
      longestWaitingTime: '00:02',
      nextDeadline: '11:26',
      sorting: '08:45',
      editors: 1,
      potential: 19,
      forced: 0,
      idle: 0,
      freelancer: 0,
      zeroHours: 0, zeroHoursFlag: 0,
      twoHours: 0, twoHoursFlag: 0,
      fourHours: 0, fourHoursFlag: 0,
      eightHours: 0, eightHoursFlag: 0,
      twelveHours: 161, twelveHoursFlag: 0,
      sixteenHours: 161, sixteenHoursFlag: 0,
      twentyFourHours: 174, twentFourHoursFlag: 0,
      fourtyEightHours: 174,
      seventyTwoHours: 174,
      avgIpt: 183.99,
      avgRej: 0.0588
    },
    {
      name: 'Bumblebee',
      pipeline: 0,
      notAssigned: 1,
      assigned: 16,
      longestWaitingTime: '00:02',
      nextDeadline: '11:26',
      sorting: '08:45',
      editors: 1,
      potential: 19,
      forced: 0,
      idle: 0,
      freelancer: 0,
      zeroHours: 0, zeroHoursFlag: 0,
      twoHours: 0, twoHoursFlag: 0,
      fourHours: 0, fourHoursFlag: 0,
      eightHours: 0, eightHoursFlag: 0,
      twelveHours: 161, twelveHoursFlag: 0,
      sixteenHours: 161, sixteenHoursFlag: 0,
      twentyFourHours: 174, twentFourHoursFlag: 0,
      fourtyEightHours: 174,
      seventyTwoHours: 174,
      avgIpt: 204.83,
      avgRej: 0.0682
    },
    {
      name: 'Optimus',
      pipeline: 0,
      notAssigned: 1,
      assigned: 16,
      longestWaitingTime: '00:02',
      nextDeadline: '11:26',
      sorting: '08:45',
      editors: 1,
      potential: 19,
      forced: 0,
      idle: 0,
      freelancer: 0,
      zeroHours: 0, zeroHoursFlag: 0,
      twoHours: 0, twoHoursFlag: 0,
      fourHours: 0, fourHoursFlag: 0,
      eightHours: 0, eightHoursFlag: 0,
      twelveHours: 161, twelveHoursFlag: 0,
      sixteenHours: 161, sixteenHoursFlag: 0,
      twentyFourHours: 174, twentFourHoursFlag: 0,
      fourtyEightHours: 174,
      seventyTwoHours: 174,
      avgIpt: 189.18,
      avgRej: 0.0576
    },
    {
      name: 'McQueen',
      pipeline: 0,
      notAssigned: 1,
      assigned: 16,
      longestWaitingTime: '00:02',
      nextDeadline: '11:26',
      sorting: '08:45',
      editors: 1,
      potential: 19,
      forced: 0,
      idle: 0,
      freelancer: 0,
      zeroHours: 0, zeroHoursFlag: 0,
      twoHours: 0, twoHoursFlag: 0,
      fourHours: 0, fourHoursFlag: 0,
      eightHours: 0, eightHoursFlag: 0,
      twelveHours: 161, twelveHoursFlag: 0,
      sixteenHours: 161, sixteenHoursFlag: 0,
      twentyFourHours: 174, twentFourHoursFlag: 0,
      fourtyEightHours: 174,
      seventyTwoHours: 174,
      avgIpt: 497.42,
      avgRej: 0.1269
    },
    {
      name: 'Mater',
      pipeline: 0,
      notAssigned: 1,
      assigned: 16,
      longestWaitingTime: '00:02',
      nextDeadline: '11:26',
      sorting: '08:45',
      editors: 1,
      potential: 19,
      forced: 0,
      idle: 0,
      freelancer: 0,
      zeroHours: 0, zeroHoursFlag: 0,
      twoHours: 0, twoHoursFlag: 0,
      fourHours: 0, fourHoursFlag: 0,
      eightHours: 0, eightHoursFlag: 0,
      twelveHours: 161, twelveHoursFlag: 0,
      sixteenHours: 161, sixteenHoursFlag: 0,
      twentyFourHours: 174, twentFourHoursFlag: 0,
      fourtyEightHours: 174,
      seventyTwoHours: 174,
      avgIpt: 245.33,
      avgRej: 0.0963
    },
    {
      name: 'The Flash',
      pipeline: 0,
      notAssigned: 1,
      assigned: 16,
      longestWaitingTime: '00:02',
      nextDeadline: '11:26',
      sorting: '08:45',
      editors: 1,
      potential: 19,
      forced: 0,
      idle: 0,
      freelancer: 0,
      zeroHours: 0, zeroHoursFlag: 0,
      twoHours: 0, twoHoursFlag: 0,
      fourHours: 0, fourHoursFlag: 0,
      eightHours: 0, eightHoursFlag: 0,
      twelveHours: 161, twelveHoursFlag: 0,
      sixteenHours: 161, sixteenHoursFlag: 0,
      twentyFourHours: 174, twentFourHoursFlag: 0,
      fourtyEightHours: 174,
      seventyTwoHours: 174,
      avgIpt: 342.40,
      avgRej: 0.0955
    },
    {
      name: 'Cyborg',
      pipeline: 0,
      notAssigned: 1,
      assigned: 16,
      longestWaitingTime: '00:02',
      nextDeadline: '11:26',
      sorting: '08:45',
      editors: 1,
      potential: 19,
      forced: 0,
      idle: 0,
      freelancer: 0,
      zeroHours: 0, zeroHoursFlag: 0,
      twoHours: 0, twoHoursFlag: 0,
      fourHours: 0, fourHoursFlag: 0,
      eightHours: 0, eightHoursFlag: 0,
      twelveHours: 161, twelveHoursFlag: 0,
      sixteenHours: 161, sixteenHoursFlag: 0,
      twentyFourHours: 174, twentFourHoursFlag: 0,
      fourtyEightHours: 174,
      seventyTwoHours: 174,
      avgIpt: 302.59,
      avgRej: 0.0963
    },
    {
      name: 'Burberry',
      pipeline: 0,
      notAssigned: 1,
      assigned: 16,
      longestWaitingTime: '00:02',
      nextDeadline: '11:26',
      sorting: '08:45',
      editors: 1,
      potential: 19,
      forced: 0,
      idle: 0,
      freelancer: 0,
      zeroHours: 0, zeroHoursFlag: 0,
      twoHours: 0, twoHoursFlag: 0,
      fourHours: 0, fourHoursFlag: 0,
      eightHours: 0, eightHoursFlag: 0,
      twelveHours: 161, twelveHoursFlag: 0,
      sixteenHours: 161, sixteenHoursFlag: 0,
      twentyFourHours: 174, twentFourHoursFlag: 0,
      fourtyEightHours: 174,
      seventyTwoHours: 174,
      avgIpt: 530.89,
      avgRej: 0.1668
    },
    {
      name: 'Finalize',
      pipeline: 0,
      notAssigned: 1,
      assigned: 16,
      longestWaitingTime: '00:02',
      nextDeadline: '11:26',
      sorting: '08:45',
      editors: 1,
      potential: 19,
      forced: 0,
      idle: 0,
      freelancer: 0,
      zeroHours: 0, zeroHoursFlag: 0,
      twoHours: 0, twoHoursFlag: 0,
      fourHours: 0, fourHoursFlag: 0,
      eightHours: 0, eightHoursFlag: 0,
      twelveHours: 161, twelveHoursFlag: 0,
      sixteenHours: 161, sixteenHoursFlag: 0,
      twentyFourHours: 174, twentFourHoursFlag: 0,
      fourtyEightHours: 174,
      seventyTwoHours: 174,
      avgIpt: 143.65,
      avgRej: 0.0334
    },
    {
      name: 'VPE Auto Finalize',
      pipeline: 0,
      notAssigned: 1,
      assigned: 16,
      longestWaitingTime: '00:02',
      nextDeadline: '11:26',
      sorting: '08:45',
      editors: 1,
      potential: 19,
      forced: 0,
      idle: 0,
      freelancer: 0,
      zeroHours: 0, zeroHoursFlag: 0,
      twoHours: 0, twoHoursFlag: 0,
      fourHours: 0, fourHoursFlag: 0,
      eightHours: 0, eightHoursFlag: 0,
      twelveHours: 161, twelveHoursFlag: 0,
      sixteenHours: 161, sixteenHoursFlag: 0,
      twentyFourHours: 174, twentFourHoursFlag: 0,
      fourtyEightHours: 174,
      seventyTwoHours: 174,
      avgIpt: 124.46,
      avgRej: 0.0392
    },
    {
      name: 'Fix',
      pipeline: 0,
      notAssigned: 1,
      assigned: 16,
      longestWaitingTime: '00:02',
      nextDeadline: '11:26',
      sorting: '08:45',
      editors: 1,
      potential: 19,
      forced: 0,
      idle: 0,
      freelancer: 0,
      zeroHours: 0, zeroHoursFlag: 0,
      twoHours: 0, twoHoursFlag: 0,
      fourHours: 0, fourHoursFlag: 0,
      eightHours: 0, eightHoursFlag: 0,
      twelveHours: 161, twelveHoursFlag: 0,
      sixteenHours: 161, sixteenHoursFlag: 0,
      twentyFourHours: 174, twentFourHoursFlag: 0,
      fourtyEightHours: 174,
      seventyTwoHours: 174,
      avgIpt: 171.88,
      avgRej: 0.0860
    },
  ];
}
